# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ldty9TVR61C2VOqDEX8X9Uq6jJz4u1H4
"""

import pandas as pd
teacher= pd.DataFrame({

                       'Ism':['Halilov.D', 'Djalilov.M', 'Araboyev.A', 'Aloydinov.M', 'Qadamova.Z', 'Jo`rayeva.G','Xontorayev.S','Abdullayeva.M', 'Turdimatov.M'],
                       'Fani':['Suniy i', 'Kom. tashkil etish', 'Kiberxavsizlik', 'Kom. tashkil etish', 'Suniy i', 'Eliktronika', 'Malumotlar tuz. va algo.', 'Malumotlar tuz. va algo.', 'Kiberxavsizlik',],
                       'Dars turi':['Maruza', 'Maruza', 'Amaliiy', 'Amaliy', 'Amaliy', 'Maruza va Amaliy', 'Maruza', 'Amaliy', 'Maruza',],
})
print (teacher)

teacher.to_excel('teacher.xlsx')